### ISSUE TITLE
Practica chida

### ISSUE THREAD

**Issue by UsuarioIncognito** [SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-pavos2#1]
[1AS_MAT_DISC_PRACTICA_1_.pdf](https://github.com/user-attachments/files/18065378/1AS_MAT_DISC_PRACTICA_1_.pdf)

**Comment by Irwingferia** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
